POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Mark"
}

###

GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWFyayIsImlhdCI6MTU4ODI3NjI4NywiZXhwIjoxNTg4Mjc2MzEyfQ.39RWGvXFt_5kPZPS8crw6obyEB_gRombhebXEB48WZM

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWFyayIsImlhdCI6MTU4ODI3MDY1OX0.a3g8PoRhxEOHZZlbAsRMT6lZXXeIeadnX_pq9Qw_xYE"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWFyayIsImlhdCI6MTU4ODI3OTkwN30.865BJ4qwZahOPvwX3Grvrz9mNepzZAoKj4azYGHThbc"
}
